### ISSUE TITLE
30B model doesn't load

### ISSUE THREAD

**Issue by RCasatta** [setzer22/llama-rs#13] opened 2023-03-15 16:23 UTC
Following the same steps works for 7B and 13B model, with the 30B parameters I get

```
thread 'main' panicked at 'Could not load model: Tensor tok_embeddings.weight has the wrong size in model file', llama-rs/src/main.rs:39:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by philpax** [comment] 2023-03-16 01:40
Does the 30B model work for you in llama.cpp?

**Comment by rfurlan** [comment] 2023-03-16 01:49
Yes, it works as expected in llama.cpp

**Comment by setzer22** [comment] 2023-03-16 07:59
This could be a discrepancy in size due to integer promotion rules / a potential overflow, since the sizes for 30B are gonna be larger. More liberal use of usize (#18) would probably help here.

Need to see if I can repro this.

**Comment by mwbryant** [comment] 2023-03-16 16:26
I have the same error, happens on https://github.com/setzer22/llama-rs/blob/3ce15b1200a3419d31c2dbe44b4ebd569370409a/llama-rs/src/llama.rs#L446 with tensor.nelements() = 212992000, n_parts = 3, and nelementes = 53248000

llama.cpp returns the same values with n_parts = 4 instead so it's not an i32 issue, https://github.com/setzer22/llama-rs/blob/3ce15b1200a3419d31c2dbe44b4ebd569370409a/llama-rs/src/llama.rs#L102 should say 4 instead of 3 (4 is what llama.cpp has as well).

Making this changes makes the model work for me.  (Aside: The load time for the 30B model is brutal, if it can be parallel then it's absolutely worth it)

**Comment by setzer22** [comment] 2023-03-16 19:19
Pushed! Sorry about that :sweat_smile:  It was just a typo on my end.

**Comment by setzer22** [comment] 2023-03-16 21:27
I was just able to load 30B with the changes on main, but I'll wait for others to confirm before closing the issue.

**Comment by RCasatta** [comment] 2023-03-16 23:03
I confirm I can now load the 30B model with main.

But it fits barely if you have 64GB of ram

**Comment by setzer22** [comment] 2023-03-16 23:27
@RCasatta  you mean the f16 version? Yes, I wasn't able to load that one on my machine (32GB). But I'm able to load the quantized one just fine.

Anyway, closing since the issue is solved, but feel free to keep discussing 😄

**Closed by setzer22** 2023-03-16 23:27 UTC

**Comment by RCasatta** [comment] 2023-03-17 06:44
> @RCasatta you mean the f16 version?

Yes I mean the f16 version, I didn't know you can quantize 😅
